development:
  adapter: postgresql
  database: tours
  username: afzal
  password: afzal
  encoding: utf8
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: tours_test
  encoding: utf8
  username: afzal
  password: afzal
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: tours
  encoding: utf8  
  username: afzal
  password: afzal
  host: localhost

  pool: 5
  timeout: 5000
